use_frameworks!

target 'DPSwiftExtension_Example' do
  pod 'DPSwiftExtension', :path => '../'

  target 'DPSwiftExtension_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
